//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Role.proto
namespace com.yyq.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VO_Skill")]
  public partial class VO_Skill : global::ProtoBuf.IExtensible
  {
    public VO_Skill() {}
    
    private int _skillGroupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillGroupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillGroupId
    {
      get { return _skillGroupId; }
      set { _skillGroupId = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_RoleInfo")]
  public partial class CS_RoleInfo : global::ProtoBuf.IExtensible
  {
    public CS_RoleInfo() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<VO_Skill> _skills = new global::System.Collections.Generic.List<VO_Skill>();
    [global::ProtoBuf.ProtoMember(2, Name=@"skills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<VO_Skill> skills
    {
      get { return _skills; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}